language: python
sudo: false

script:
- pip install .
- py.test
- coverage run tests/test_*.py
- export BACKUPS_FILE=examples/backups.yaml
- backups help
- backups version
- backups ls
- backups show acme
- backups run acme --dryrun

after_success:
- codecov

notifications:
  on_failure: always
  email:
    recipients:
    - ptdorf@gmail.com
