language: python
sudo: false

script:
- pip install .
- py.test
- coverage run tests/test_*.py

after_success:
- codecov

notifications:
  on_failure: always
  email:
    recipients:
    - ptdorf@gmail.com
